version: "3.9"

services:
  auth-ms:
    build: ../auth-ms
    ports:
      - "4002:4002"
    env_file:
      - ../.env
    volumes:
      - ../auth-ms:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev