version: "3.9"

services:
  media-ms:
    build: ../media-ms
    ports:
      - "4004:4004"
    env_file:
      - ../.env
    volumes:
      - ../media-ms:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev