version: "3.9"

services:
  orders-ms:
    build: ../orders-ms
    ports:
      - "4007:4007"
    env_file:
      - ../.env
    volumes:
      - ../orders-ms:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev